### ISSUE TITLE
Build on star 

### ISSUE THREAD

**Issue by RicoP** [NewChromantics/MinimalUnityPlugin#2]
You actually start the build process every time someone stars/watches your project. I got a fail message in my news list because of it. 

[  watch:](https://github.com/NewChromantics/MinimalUnityPlugin/blob/cf4d3716d168db6b9e612a03ccfb74a2e67bc116/.github/workflows/BuildWindowsDll.yml#L11)

**Comment by SoylentGraham** [comment]
Good catch, ta!
